### ISSUE TITLE
Lxml 3.7.3 (and beautifulsoup 4.5.3 / 4.6.0) crashes with SIGSEGV on OS X

### ISSUE THREAD

**Issue by tendres** [afiskon/postgresql-fts-example#1]
Hi - I am getting the following error when running ./parse.py enwiki-20170401-pages-articles.xml.
....
Processing page 367 of 17434651 (0.002105003421060737%) with title 'Aspect ratio'
Processing page 368 of 17434651 (0.0021107391252053165%) with title 'Auto racing'

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Any suggestions?

**Comment by afiskon** [comment]
Wow, SIGSEGV is very surprising :) What version of Python and libraries are you using? Could you run python interpreter under gdb and print a stacktrace (bt) right after segmentation fault happen?

**Comment by tendres** [comment]
Running 3.6.1 on OS X 10.11.6 - postgres 9.6.2
appdirs==1.4.3
beautifulsoup4==4.5.3
lxml==3.7.3
packaging==16.8
py-postgresql==1.2.1
pyparsing==2.2.0
six==1.10.0

I tried upgrading beautifulsoup4 to 4.6.0 and it still failed but in a different repeatable spot.
...
Processing page 566 of 17434651 (0.0032464085458320906%) with title 'Apache webserver'
Processing page 567 of 17434651 (0.0032521442499766702%) with title 'Apatosaurus'

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

I will try to provide a stacktrace shortly. Thank you!

**Comment by tendres** [comment]
I am unable to get gdb running on my machine and PyCharm debugger is exiting without a stacktrace. It appears as though how far it gets is related to the speed of loading - while trying to debug (and loading more slowly) it gets further along before the SIGSEGV occurs. With just a vanilla run (loading fast) it barks earlier.

**Comment by afiskon** [comment]
This is very unfortunate, but I'm afraid there is not much I can do since I don't even have OS X. I suggest to report this issue to beautifulsoup developers. It looks like the best way to do it is via Google Group https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup

In case you'll find a way to fix it somehow in Python code please don't hesitate to send a patch.

**Comment by tendres** [comment]
I was able to get gdb running - here's the stacktrace. Hope it helps.

Processing page 366 of 17434651 (0.0020992677169161572%) with title 'Anatoly Karpov'
Processing page 367 of 17434651 (0.002105003421060737%) with title 'Aspect ratio'
Processing page 368 of 17434651 (0.0021107391252053165%) with title 'Auto racing'

Program received signal SIGSEGV, Segmentation fault.

0x00007fff959c8421 in xmlSHRINK () from /usr/lib/libxml2.2.dylib

(gdb) bt

#0  0x00007fff959c8421 in xmlSHRINK () from /usr/lib/libxml2.2.dylib
#1  0x00007fff959d4811 in xmlParseTryOrFinish () from /usr/lib/libxml2.2.dylib
#2  0x00007fff959d45cd in xmlParseChunk () from /usr/lib/libxml2.2.dylib
#3  0x000000010306cc18 in __pyx_f_4lxml_5etree_11_FeedParser_close ()
   from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so
#4  0x00000001030f6b3e in __pyx_pw_4lxml_5etree_11_FeedParser_3close ()
  from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so
#5  0x0000000103155e8f in __Pyx_CyFunction_CallAsMethod ()
   from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so
#6  0x000000010000e8d4 in PyNumber_InPlacePower ()
   from /Library/Frameworks/Python.framework/Versions/3.6/Python
#7  0x0000000000000000 in ?? ()

**Comment by afiskon** [comment]
OK, this is most definitely a bug in lxml module. I would recommend to report it to the lxml developers: http://lxml.de/#bug-tracker

It would be a good idea to include values of the variables and arguments on every stack frame.  To show variables and arguments in current frame:

(gdb) info args
(gdb) info locals

To change the frame:

(gdb) f 1
(gdb) f 2

It's also worth considering to upload a coredump on some file hosting (e.g. Dropbox). Unfortunately I'm not an expert in OS X and I don't know how coredumps are created on this system. You can try to create a coredump using gdb:

(gdb) generate-core-file
